In [2]:
import numpy as np

<h3 style='color:blue'>Calculate profit/loss from revenue and expenses</h3>

In [2]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

<h3 style='color:blue'> @ (Matrix dot product) vs * (element-to-element multiplicati0n) </h3>

In [22]:
# Matrix Multiplication (dot product) exampple
# https://stackoverflow.com/questions/66619157/numpy-dot-product-of-matrix-and-array
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([1, 2])
print('a:')
print(a)
print('b:', b)

print('Matrix Multiplication:')
print('a.dot(b):')
print(a.dot(b))
print()
# a = [[1 2]
#      [3 4]
#      [5 6]]
# b:   [1 2]
# a . b = [ 3 x 2 ] [2 x 1] = [3 x 1]
#        ---    ---   -- --   --            ---   --   --
#        | 1    2 |   | 1 |   | 1 x 1 + 2 x 2 |   |  5  |
#        | 3    4 | . |   | = | 3 x 1 + 4 x 2 | = |  11 |
#        | 5    6 |   | 2 |   | 5 x 1 + 6 x 2 |   |  17 |
#        ---    ---   -- --   ---           ---   --   --
print('a @ b : same as a.dot(b)')
print('a @ b :', a @ b)

a:
[[1 2]
 [3 4]
 [5 6]]
b: [1 2]
Matrix Multiplication:
a.dot(b):
[ 5 11 17]

a @ b : same as a.dot(b)
a @ b : [ 5 11 17]


In [21]:
# *: element-by-element multiplicaiton
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([1, 2])
print('a:')
print(a)
print('b:', b)
# a = [[1 2]
#      [3 4]
#      [5 6]]
# b:   [1 2]
# a . b = [ 3 x 2 ] [2 x 1] => [3 x 2 ] * [ 3 x 2] => [ 3 x 2 ]
#        ---    ---   -- --    --    ---   --    --    --            --   --     -- 
#        | 1    2 |   | 1 |    | 1   2 |   | 1  2 |    | 1 x 1  2 x 2 |   | 1   4 |
#        | 3    4 | * |   | => | 3   4 | * | 1  2 | => | 3 x 1  4 x 2 | = | 3   8 |
#        | 5    6 |   | 2 |    | 5   6 |   | 1  2 |    | 5 x 1  6 x 2 |   | 5  12 |
#        ---    ---   -- --    ---   ---   --    --    --            --   --     --
#        ---    ---   -- --
print('Matrix Multiplication:')
print('a * b:')
print(a * b)

a:
[[1 2]
 [3 4]
 [5 6]]
b: [1 2]
Matrix Multiplication:
a * b:
[[ 1  4]
 [ 3  8]
 [ 5 12]]


<h3 style='color:blue'>Calculate total sales from units and price per unit using matrix multiplication</h3>

In [6]:
# What is “*” in Numpy?
# 1. NumPy performs operations element-by-element.
# 2. Multiplying 2D arrays with * is not a matrix multiplication.
# 3. “*” an element-by-element multiplication.
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])
print('price_per_unit.shape:')
print(price_per_unit.shape)
print('price_per_unit:')
print(price_per_unit)   # [1000  400 1200]
print('units.shape:')
print(units.shape)
print('units:')
# [[30 40 50]
# [ 5 10 15]
# [ 2  5  7]]
print(units)
# 1. Expand the [1000  400 1200] into 
# [
#   [1000  400 1200]
#   [1000  400 1200]
#   [1000  400 1200]
# ]
# 2. Perform the element-by-element multiplication:
# [
#   [1000  400 1200]
#   [1000  400 1200]
#   [1000  400 1200]
# ] 
#  *
# [[30 40 50]
# [ 5 10 15]
# [ 2  5  7]]
# Multiplication (Matrix multiplication: element by element wihtout summation)
# [[ 1000 * 30      400 * 40     1200 * 50 ]     => [ 30,000      16,000     60,000 ]
#  [ 1000 * 5       400 * 10     1200 * 15]      => [  5,000       4,000     18,000 ]  
#  [ 1000 * 2       400 * 5      1200 * 7]]      => [  2,000       2,000      8,400 ]
print(price_per_unit*units)

price_per_unit.shape:
(3,)
price_per_unit:
[1000  400 1200]
units.shape:
(3, 3)
units:
[[30 40 50]
 [ 5 10 15]
 [ 2  5  7]]
[[30000 16000 60000]
 [ 5000  4000 18000]
 [ 2000  2000  8400]]


In above case numpy is using broadcasting so it expands price_per_unit array from 1 row, 3 columns to 3 row and 3 columns. Correct way to do matrix multiplication is to use dot product as shown below

In [12]:
print('price_per_unit.shape:')
print(price_per_unit.shape)
print('price_per_unit:')
print(price_per_unit)   # [1000  400 1200]
print('units.shape:')
print(units.shape)
print('units:')
# [[30 40 50]
# [ 5 10 15]
# [ 2  5  7]]
print(units)
print('dot product: [1 x 3] * [3 x 3] = [1 x 3]: np.dot(price_per_unit,units)')
#                        [[30 40 50]
#  [1000  400  1200 ] *   [ 5 10 15]
#                         [ 2  5  7]]
#  = [ 1,000 * 30 + 400 * 50 + 1,200 * 2;      1000 * 40 + 400 * 10 + 1200 * 5;     1000 * 50 + 400 * 15 + 1200 * 7]
#  = [     30,000 + 2,000    + 2,400;          40,000    + 4,000    + 6,000;           50,000 + 6,000    + 8,400]
#  = [     34,400;                             50,000;                                 64,400] 
# =  [34400; 50000; 64400]
print(np.dot(price_per_unit,units))

price_per_unit.shape:
(3,)
price_per_unit:
[1000  400 1200]
units.shape:
(3, 3)
units:
[[30 40 50]
 [ 5 10 15]
 [ 2  5  7]]
dot product: [1 x 3] * [3 x 3] = [1 x 3]: np.dot(price_per_unit,units)
[34400 50000 64400]


# Solution 1: Convert USD revenues to INR

In [5]:
revenues_usd = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
revenues_inr = 75*revenues_usd
revenues_inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

# Solution 2: Calculate total flowers sale every month for divine flowers shop

In [6]:
units_sold = np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit = np.array([20,30,15])
total_sales_amount = np.dot(price_per_unit,units_sold)
total_sales_amount

array([1900, 2640, 1430])